### ISSUE TITLE
Covid Ss Treated as Fs 

### ISSUE THREAD

**Issue by MachoKing** [cougargrades/web#149]
Hello, 

I've been looking through the GPAs and the GPAs are wrong. It seems like during the covid period Ss are treated as Fs for the calculation of the GPAs. This gives professors inaccurate GPAs for those semesters.  Please fix this issue! Students have stopped enrolling in my course!!!

**Comment by au5ton** [comment]
Hello,

I am sorry if any of the data within CougarGrades is inaccurate or misleading. Let's get to the bottom of this.

On the site, there is a "GPA" and other measurements that are seen immediately below a Course or Instructor's name (see below)

<img width="491" alt="Screenshot 2023-07-11 at 12 39 29 PM" src="https://github.com/cougargrades/web/assets/4109551/6d3bbe81-d3b7-4497-9972-d8d369825cb5">

These measurements are an _average_ of averages per section (something that CougarGrades calculates). For example, the [raw data we receive from UH](https://github.com/cougargrades/publicdata/blob/5521b25a29aba02e7b4cd58b3df1f399a8f9530c/documents/edu.uh.grade_distribution/Grade%20Distribution%202022-02%20(Summer%202022).csv) looks very similar to how it is presented on the site:

<img width="1184" alt="Screenshot 2023-07-11 at 12 45 44 PM" src="https://github.com/cougargrades/web/assets/4109551/687e01ff-9a2b-472e-b475-ca93f2fd8491">

**Crucially, the "GPA" column in this table is not something that was calculated by CougarGrades, but was exactly what was provided by the University.**

This is made a little worse by the fact that [UH did not provide me with any NCR data for Spring 2020](https://blog.cougargrades.io/2020/07/15/new-data/), so for that semester it may look like 0 students had any "NCR" grades.

In the past, there was an issue where some sections had a missing or placeholder value of 0 for their "GPA" and this was improperly handled by CougarGrades. It has since been addressed and the site updated.

For more information, see:
- https://cougargrades.io/faq/data-accuracy
- Issue #115 

**Except the aforementioned issue and its solution, CougarGrades currently treats the value within this UH-provided "GPA" column as the absolute truth (for better or worse).**

These unusually low GPAs for the COVID period have been noticed in the past, and I don't really know how to explain for them. A while back, I added a [new FAQ entry to address it](https://cougargrades.io/faq/interim-grading-theory) and give the leading theory speculating why the numbers are like that.

Undeniably, the source of these irregular GPA values are from UH itself. The long-standing question has been what to do about it (if any).

**Comment by au5ton** [comment]
Does the above comment make any sense? @MachoKing

**Comment by au5ton** [comment]
Closing as this is the same as #152

**Comment by au5ton** [comment]
To help alleviate some of the confusion regarding this, the site has been updated to display a warning if the GPA that UH provided and a calculated GPA are too different.

To learn more, we've updated our FAQ: https://next.cougargrades.io/faq/interim-grading-theory
