### ISSUE TITLE
's' should not  be count as 0 , that's misleading

### ISSUE THREAD

**Issue by hutuhehe** [cougargrades/web#152]
while today i checked the COS 6342 given by professor Mukheriee,Arjun ,I was surprised to find the average GPA in spring  is 2.11, that's extremely low

As  I examed the grade carefully, it's because 7 students got 's' that really lower the average GPA so much.
From reddit,  I was told 's' was counted  as nothing , that is '0'. 

Of course in the  FAQ section, it surely gives out the situation when GPA is not accurate
But the problem is , most of us, without beforehand reading the FAQ,  that inaccurate  GPA information  is  extremely misleading  expecially when there shows a substantial portion of  Ss
here I suggest three ways of solving this problem
1. Not include all the students got 's' to the average GPA calculation,  treat it as 'NA'
1. Count 's' as a 3.0 GPA, that's much more accurate than count as '0'
2. Make the inaccurate situation very clear when showing GPA distribution

Having  no information is bad,  but  get misleading information is even worse

**Comment by au5ton** [comment]
Hi @hutuhehe , thank you for using CougarGrades. Despite its flaws, I hope you found the site valuable in your goals as a student.

In [this FAQ entry](https://cougargrades.io/faq/interim-grading-theory) I go over how some numbers during the pandemic don't add and are confusing.

In the course your are specifically referencing, this is the specific section I think you are referring to:
![image](https://github.com/cougargrades/web/assets/4109551/dd387d4e-37b7-4508-a55a-5f93a07920c6)
_Source: https://cougargrades.io/c/COSC%206342_

As stated in the FAQ, "this data is exactly as UH provided it (with no official explanation)". I really wish UH gave me data that didn't create such an ambiguous situation, but it's what they did, and I don't intend on modifying that data.

By definition, the S/NCR shrouds what the students would have earned had the pass/fail system not been implemented. If I were to replace the GPA with something manually calculated _without the S column_, that would be replacing the number UH provided with **something inflated and less significant**. If I were to replace the GPA with something manually calculated where I assumed that S meant C or D, that's a big assumption and is a completely manufactured number!

> shows a substantial portion of Ss

Irrespective of "AVG GPA" column thing, a substantial portion of students taking Ss _IS_ a red flag. By using the ambiguous but sometimes harsh number that an official source provided me, that draws attention to it.

In the past, some (typically graduate-level) courses and instructors were [unfairly represented due to a bug](https://blog.cougargrades.io/2023/02/26/update/). This is something that matters to me and was fixed. However, the S/NCR grades are here to stay.

**Comment by au5ton** [comment]
To help alleviate some of the confusion regarding this, the site has been updated to display a warning if the GPA that UH provided and a calculated GPA are too different.

To learn more, we've updated our FAQ: https://next.cougargrades.io/faq/interim-grading-theory

**Comment by hutuhehe** [comment]
appreciate all the updates. Cougargrade is truly excellent in its work!

Austin Jackson ***@***.***> 于2024年1月7日周日 23:42写道：
