### ISSUE TITLE
Outdated dev env setup readme 

### ISSUE THREAD

**Issue by yj7o5** [cougargrades/web#27]
Hi @au5ton 

I was setting the project up locally and saw that its a bit outdated as the API_KEY setup in the .env.development no longer contains the 'FIREBASE' keyword. I can go ahead fix the docs, if you like :) ...

Oh and I am just another cougar who loves OSS.

**Comment by au5ton** [comment]
Thank you for reaching out and showing interest in the project. ❤️  I will admit that the documentation is outdated, but that's because a lot of major changes are still (albeit, less actively) being worked on over on the [PoC4](https://github.com/cougargrades/web/tree/PoC4) branch. In that branch (at least, currently), we've switched away from [create-react-app](https://github.com/facebook/create-react-app) in favor of [Snowpack](https://github.com/pikapkg/snowpack), Typescript, and a major redesign.

If you want to follow along for yourself, changes made to the PoC4 branch are automatically deployed to https://cougargrades-testing.web.app

Currently, UI development has halted and is waiting for API and database to finalize over at [cougargrades/api, "TS" branch](https://github.com/cougargrades/api/tree/ts) and in [cougargrades/types](https://github.com/cougargrades/types).

For the overall status of the project, Github Projects is a lifesaver:

API 2.0.0: https://github.com/orgs/cougargrades/projects/1
Web Redesign: https://github.com/orgs/cougargrades/projects/2

**Comment by au5ton** [comment]
I closed this because the environment setup will be different when the next version is finalized and I will write it there.
